[Interface]
PrivateKey = YN3dzy+01yWVVH29e7azPPYBDENMauSsFW1txWpY120=
Address = 10.202.10.118
MTU = 1420
DNS = 8.8.8.8, 8.8.4.4

[Peer]
PublicKey = CViMrWjsWmgo9osKfma5RXmwhH4gEsr+NFhqQ8Dwc0I=
PresharedKey = 2t/DVC7jEPevIFxfd4J05YpnKZrdXPxYMgxkkZkUMM4=
Endpoint = Lord.host786phpvvbchostvps.dufdtjj.xyz:2803
PersistentKeepalive = 25